# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('pushKey', models.CharField(max_length=30)),
                ('avatar', models.ImageField(blank=True, default='null', upload_to='./avatar/')),
                ('avatarThumb', models.ImageField(blank=True, default='null', upload_to='./avatar/thumb')),
                ('birthday', models.CharField(max_length=30)),
                ('simpleProfile', models.CharField(blank=True, max_length=30)),
                ('longProfile', models.CharField(blank=True, max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
