# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovemarker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pushKey',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
